@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'date' 'sysdate' 'sysdate-1' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'number' '2.0' '1.99' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'interval year to month' '''2-1''' '''2-0''' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'interval day to second' '''2 01:00:00''' '''2 00:59:59''' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'timestamp' 'to_timestamp(''1997-01 09:26:50.13'',''YYYY-MM HH24.MI.SS.FF'')' 'to_timestamp(''1997-01 09:26:50.12'',''YYYY-MM HH24.MI.SS.FF'')' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'timestamp with time zone' 'to_timestamp_tz(''1997 +01:00'',''YYYY TZR'')' 'to_timestamp_tz(''1997 +02:00'',''YYYY TZR'')' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'timestamp with local time zone' 'to_timestamp_tz(''1997 +01:00'',''YYYY TZR'')' 'to_timestamp_tz(''1997 +02:00'',''YYYY TZR'')' 'ut_utils.tr_success'"

@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'date' 'sysdate' 'sysdate' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'number' '1.99' '1.99' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'interval year to month' '''2-0''' '''2-0''' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'INTERVAL DAY TO SECOND' '''2 00:59:01''' '''2 00:59:01''' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'timestamp' 'to_timestamp(''1997 09:26:50.12'',''YYYY HH24.MI.SS.FF'')' 'to_timestamp(''1997 09:26:50.12'',''YYYY HH24.MI.SS.FF'')' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'timestamp with time zone' 'to_timestamp_tz(''1997 +01:00'',''YYYY TZR'')' 'to_timestamp_tz(''1997 +01:00'',''YYYY TZR'')' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'timestamp with local time zone' 'to_timestamp_tz(''1997 +01:00'',''YYYY TZR'')' 'to_timestamp_tz(''1997 +01:00'',''YYYY TZR'')' 'ut_utils.tr_success'"

@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'date' 'sysdate-1' 'sysdate' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'number' '1.0' '1.01' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'interval year to month' '''2-1''' '''2-2''' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'interval day to second' '''2 00:59:58''' '''2 00:59:59''' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'timestamp' 'to_timestamp(''1997 09:26:50.12'',''YYYY HH24.MI.SS.FF'')' 'to_timestamp(''1997 09:26:50.13'',''YYYY HH24.MI.SS.FF'')' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'timestamp with time zone' 'to_timestamp_tz(''1997 +03:00'',''YYYY TZR'')' 'to_timestamp_tz(''1997 +02:00'',''YYYY TZR'')' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_greater_or_equal.sql 'timestamp with local time zone' 'to_timestamp_tz(''1997 +03:00'',''YYYY TZR'')' 'to_timestamp_tz(''1997 +02:00'',''YYYY TZR'')' 'ut_utils.tr_failure'"
