create or replace package test_TE_EMPLOYEE
IS
   PROCEDURE test_setup;

   PROCEDURE test_teardown;

   PROCEDURE test_DEL1;
   PROCEDURE test_DELBY_EMP_DEPT_LOOKUP;
   PROCEDURE test_DELBY_EMP_JOB_LOOKUP;
   PROCEDURE test_DELBY_EMP_MGR_LOOKUP;
   PROCEDURE test_INS1;
   PROCEDURE test_UPD1;
   PROCEDURE test_UPD$HIRE_DATE1;
   PROCEDURE test_UPD$SALARY1;

   PROCEDURE test_EMP_DEPT_LOOKUPROWCOUNT;
   PROCEDURE test_EMP_JOB_LOOKUPROWCOUNT;
   PROCEDURE test_EMP_MGR_LOOKUPROWCOUNT;
   PROCEDURE test_HIRE_DATE$VAL;
   PROCEDURE test_I_EMPLOYEE_NAME$ROW;
   PROCEDURE test_I_EMPLOYEE_NAME$VAL;
   PROCEDURE test_ONEROW;
   PROCEDURE test_PKYROWCOUNT;
   PROCEDURE test_ROWCOUNT;
   PROCEDURE test_SALARY$VAL;

END test_TE_EMPLOYEE;
/
