#!/bin/sh
set -e

clientPath=${1%/}
projectPath=${2%/}
scanPath=$3
outFileName=$4
sqlParamName=$5

# All parameters are required.
invalidArgs=0
[ -z "$clientPath"   ] && invalidArgs=1
[ -z "$projectPath"  ] && invalidArgs=1
[ -z "$scanPath"     ] && invalidArgs=1
[ -z "$outFileName"  ] && invalidArgs=1
[ -z "$sqlParamName" ] && invalidArgs=1

if [ $invalidArgs -eq 1 ]; then
    echo Usage: ut_run.sh "client_path" "project_path" "scan_path" "out_file_name" "sql_param_name"
    exit 1
fi

fullOutPath="$clientPath/$outFileName"
fullScanPath="$projectPath/$scanPath"

# If scan path is "-", bypass the file list generation.
if [ "$scanPath" = "-" ]; then
    echo "begin" > $fullOutPath
    echo "  open :$sqlParamName for select null from dual;" >> $fullOutPath
    echo "end;" >> $fullOutPath
    echo "/" >> $fullOutPath
    exit 0
fi

echo "declare" > $fullOutPath
echo "    l_list ut_varchar2_list := ut_varchar2_list();" >> $fullOutPath
echo "begin" >> $fullOutPath
for f in $(find $fullScanPath/* -type f | sed "s|$projectPath/||"); do
    echo "    l_list.extend; l_list(l_list.last) := '$f';" >> $fullOutPath
done
echo "    open :$sqlParamName for select * from table(l_list);" >> $fullOutPath
echo "end;" >> $fullOutPath
echo "/" >> $fullOutPath
