Clear Screen
set echo off
set feedback off
prompt RunExampleComplexSuiteWithCustomDBMSOutputReporter
@@RunExampleComplexSuiteWithCustomDBMSOutputReporter.sql
prompt RunExampleTestSuite
@@RunExampleTestSuite.sql
prompt RunExampleTestSuiteWithCustomDBMSOutputReporter
@@RunExampleTestSuiteWithCustomDBMSOutputReporter.sql
prompt RunExampleTestSuiteWithDBMSOutputReporter
@@RunExampleTestSuiteWithDBMSOutputReporter.sql
prompt RunExampleTestThroughBaseClass
@@RunExampleTestThroughBaseClass.sql
prompt TestPackageName
@@TestPackageName.sql
prompt TestProcedureName
@@TestProcedureName.sql
prompt TestOwnerName
@@TestOwnerName.sql
prompt TestSetupProcedureName
@@TestSetupProcedureName.sql
prompt TestTeardownProcedureName
@@TestTeardownProcedureName.sql
