@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'blob' 'NULL' 'NULL' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'boolean' 'NULL' 'NULL' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'clob' 'NULL' 'NULL' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'date' 'NULL' 'NULL' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'number' 'NULL' 'NULL' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'timestamp' 'NULL' 'NULL' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'timestamp with local time zone' 'NULL' 'NULL' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'timestamp with time zone' 'NULL' 'NULL' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'varchar2(4000)' 'NULL' 'NULL' 'ut_utils.tr_success'"
