@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'blob' 'to_blob(''abc'')' 'not_to_be_null' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'boolean' 'true' 'not_to_be_null' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'clob' '''abc''' 'not_to_be_null' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'date' 'sysdate' 'not_to_be_null' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'number' '1234' 'not_to_be_null' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'timestamp' 'systimestamp' 'not_to_be_null' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'timestamp with local time zone' 'systimestamp' 'not_to_be_null' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'timestamp with time zone' 'systimestamp' 'not_to_be_null' 'ut_utils.tr_success'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'varchar2(4000)' '''abc''' 'not_to_be_null' 'ut_utils.tr_success'"

@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'blob' 'NULL' 'not_to_be_null' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'boolean' 'NULL' 'not_to_be_null' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'clob' 'NULL' 'not_to_be_null' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'date' 'NULL' 'not_to_be_null' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'number' 'NULL' 'not_to_be_null' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'timestamp' 'NULL' 'not_to_be_null' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'timestamp with local time zone' 'NULL' 'not_to_be_null' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'timestamp with time zone' 'NULL' 'not_to_be_null' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.unuary_comparator.scalar.common.sql 'varchar2(4000)' 'NULL' 'not_to_be_null' 'ut_utils.tr_failure'"
