@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'blob' 'to_blob(''abc'')' 'NULL' '%to equal:%NULL%'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'boolean' 'false' 'NULL' '%to equal:%NULL%'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'clob' '''abc''' 'NULL' '%to equal:%NULL%'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'date' 'sysdate' 'NULL' '%to equal:%NULL%'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'number' '1234' 'NULL' '%to equal:%NULL%'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'timestamp' 'systimestamp' 'NULL' '%to equal:%NULL%'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'timestamp with local time zone' 'systimestamp' 'NULL' '%to equal:%NULL%'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'timestamp with time zone' 'systimestamp' 'NULL' '%to equal:%NULL%'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'varchar2(4000)' '''abc''' 'NULL' '%to equal:%NULL%'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'interval day to second' '''2 01:00:00''' 'NULL' '%to equal:%NULL%'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'interval year to month' '''1-1''' 'NULL' '%to equal:%NULL%'"
