@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'blob' 'to_blob(''abc'')' 'NULL' 'expected_value_string'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'boolean' 'false' 'NULL' 'expected_value_string'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'clob' '''abc''' 'NULL' 'expected_value_string'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'date' 'sysdate' 'NULL' 'expected_value_string'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'number' '1234' 'NULL' 'expected_value_string'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'timestamp' 'systimestamp' 'NULL' 'expected_value_string'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'timestamp with local time zone' 'systimestamp' 'NULL' 'expected_value_string'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'timestamp with time zone' 'systimestamp' 'NULL' 'expected_value_string'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.null_value_text.common.sql 'varchar2(4000)' '''abc''' 'NULL' 'expected_value_string'"
