@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'blob' 'NULL' 'to_blob(''abc'')' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'boolean' 'NULL' 'true' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'clob' 'NULL' '''abc''' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'date' 'NULL' 'sysdate' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'number' 'NULL' '1' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'timestamp' 'NULL' 'systimestamp' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'timestamp with local time zone' 'NULL' 'systimestamp' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'timestamp with time zone' 'NULL' 'systimestamp' 'ut_utils.tr_failure'"
@@lib/RunTest.sql "ut_expectations/common/ut.expect.to_equal.scalar.common.sql 'varchar2(4000)' 'NULL' '''abc''' 'ut_utils.tr_failure'"
