--failure when value out of range
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'date' 'sysdate' 'sysdate-2' 'sysdate-1' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'number' '2.0' '1.99' '1.999' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'varchar2(1)' '''c''' '''a''' '''b''' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp' 'systimestamp+1' 'systimestamp-1' 'systimestamp' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with local time zone' 'systimestamp+1' 'systimestamp-1' 'systimestamp' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with time zone' 'systimestamp+1' 'systimestamp-1' 'systimestamp' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval year to month' '''2-2''' '''2-0''' '''2-1''' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval day to second' '''2 01:00:00''' '''2 00:59:58''' '''2 00:59:59''' 'ut_utils.tr_failure' ''"
--success when value in range
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'date' 'sysdate' 'sysdate-1' 'sysdate+1' 'ut_utils.tr_success' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'number' '2.0' '1.99' '2.01' 'ut_utils.tr_success' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'varchar2(1)' '''b''' '''a''' '''c''' 'ut_utils.tr_success' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp' 'systimestamp' 'systimestamp-1' 'systimestamp+1' 'ut_utils.tr_success' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with local time zone' 'systimestamp' 'systimestamp-1' 'systimestamp+1' 'ut_utils.tr_success' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with time zone' 'systimestamp' 'systimestamp-1' 'systimestamp+1' 'ut_utils.tr_success' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval year to month' '''2-1''' '''2-0''' '''2-2''' 'ut_utils.tr_success' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval day to second' '''2 01:00:00''' '''2 00:59:58''' '''2 01:00:01''' 'ut_utils.tr_success' ''"
--success when value not in range
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'date' 'sysdate' 'sysdate-2' 'sysdate-1' 'ut_utils.tr_success' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'number' '2.0' '1.99' '1.999' 'ut_utils.tr_success' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'varchar2(1)' '''c''' '''a''' '''b''' 'ut_utils.tr_success' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp' 'systimestamp+1' 'systimestamp-1' 'systimestamp' 'ut_utils.tr_success' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with local time zone' 'systimestamp+1' 'systimestamp-1' 'systimestamp' 'ut_utils.tr_success' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with time zone' 'systimestamp+1' 'systimestamp-1' 'systimestamp' 'ut_utils.tr_success' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval year to month' '''2-2''' '''2-0''' '''2-1''' 'ut_utils.tr_success' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval day to second' '''2 01:00:00''' '''2 00:59:58''' '''2 00:59:59''' 'ut_utils.tr_success' 'not_'"
--failure when value not out of range
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'date' 'sysdate' 'sysdate-1' 'sysdate+1' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'number' '2.0' '1.99' '2.01' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'varchar2(1)' '''b''' '''a''' '''c''' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp' 'systimestamp' 'systimestamp-1' 'systimestamp+1' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with local time zone' 'systimestamp' 'systimestamp-1' 'systimestamp+1' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with time zone' 'systimestamp' 'systimestamp-1' 'systimestamp+1' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval year to month' '''2-1''' '''2-0''' '''2-2''' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval day to second' '''2 01:00:00''' '''2 00:59:58''' '''2 01:00:01''' 'ut_utils.tr_failure' 'not_'"

--failure when value is null
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'date' 'null' 'sysdate-1' 'sysdate+1' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'number' 'null' '1.99' '2.01' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'varchar2(1)' 'null' '''a''' '''c''' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp' 'null' 'systimestamp-1' 'systimestamp+1' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with local time zone' 'null' 'systimestamp-1' 'systimestamp+1' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with time zone' 'null' 'systimestamp-1' 'systimestamp+1' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval year to month' 'null' '''2-0''' '''2-2''' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval day to second' 'null' '''2 00:59:58''' '''2 01:00:01''' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'date' 'null' 'sysdate-2' 'sysdate-1' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'number' 'null' '1.99' '1.999' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'varchar2(1)' 'null' '''a''' '''b''' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp' 'null' 'systimestamp-1' 'systimestamp' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with local time zone' 'null' 'systimestamp-1' 'systimestamp' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with time zone' 'null' 'systimestamp-1' 'systimestamp' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval year to month' 'null' '''2-0''' '''2-1''' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval day to second' 'null' '''2 00:59:58''' '''2 00:59:59''' 'ut_utils.tr_failure' 'not_'"

--failure when lower bound is null
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'date' 'sysdate' 'null' 'sysdate+1' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'number' '2.0' 'null' '2.01' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'varchar2(1)' '''b''' 'null' '''c''' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp' 'systimestamp' 'null' 'systimestamp+1' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with local time zone' 'systimestamp' 'null' 'systimestamp+1' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with time zone' 'systimestamp' 'null' 'systimestamp+1' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval year to month' '''2-1''' 'null' '''2-2''' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval day to second' '''2 01:00:00''' 'null' '''2 01:00:01''' 'ut_utils.tr_failure' ''"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'date' 'sysdate' 'null' 'sysdate-1' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'number' '2.0' 'null' '1.999' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'varchar2(1)' '''b''' 'null' '''b''' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp' 'systimestamp+1' 'null' 'systimestamp' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with local time zone' 'systimestamp+1' 'null' 'systimestamp' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'timestamp with time zone' 'systimestamp+1' 'null' 'systimestamp' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval year to month' '''2-2''' 'null' '''2-1''' 'ut_utils.tr_failure' 'not_'"
@@lib/RunTest.sql "ut_matchers/common/ut.expect.common.be_between.sql 'interval day to second' '''2 01:00:00''' 'null' '''2 00:59:59''' 'ut_utils.tr_failure' 'not_'"
