name: Test publishing
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  upload_artifacts:
    name: Upload archives
    concurrency: upload
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      RELEASE_TAG: "v3.2.2"
      RELEASE_BODY: |
        ## What's Changed
        * Filtering by tags fixed for schemas containing suite-paths and contexts by @jgebal in https://github.com/utPLSQL/utPLSQL/pull/1325
        * Fixed issue with reporter failing to initialize by @jgebal in https://github.com/utPLSQL/utPLSQL/pull/1354
        * Fixed issue with duplicate sources from dba_source by @jgebal in https://github.com/utPLSQL/utPLSQL/pull/1355
        * Allow HTML coverage on FIPS-enabled DB by @jgebal in https://github.com/utPLSQL/utPLSQL/pull/1356
        
        
        **Full Changelog**: https://github.com/utPLSQL/utPLSQL/compare/v3.2.01...v3.2.2
      RELEASE_DATE: "2026-05-24 10:48:22"
      RELEASE_URL: "https://github.com/utPLSQL/utPLSQL/releases/tag/v3.2.2"
      TARGET_BRANCH: "develop"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ env.API_TOKEN_GITHUB }}
      - uses: c-py/action-dotenv-to-setenv@v5
        with:
          env-file: .github/variables/.env
      - uses: FranzDiebold/github-env-vars-action@v2.8.0 #https://github.com/marketplace/actions/github-environment-variables-action

#      - name: Update CHANGELOG.md with release notes
#        run: .github/scripts/update_changelog.sh

#      - name: Post release announcement to org discussions
#        env:
#          GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
#        run: .github/scripts/post_release_announcement.sh

      - name: Publish release post to utplsql.github.io
        run: .github/scripts/publish_release_post.sh

