name: Test publishing
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  upload_artifacts:
    name: Upload archives
    concurrency: upload
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      RELEASE_TAG: "v3.2.3"
      RELEASE_BODY: |
        ## What's Changed
        * Fix issue with `UT_TAP_REPORTER` on Oracle 23.26 by @jgebal in https://github.com/utPLSQL/utPLSQL/pull/1359
        * Fixed support for camelCase in context `--%name` annotation. by @jgebal in https://github.com/utPLSQL/utPLSQL/pull/1361
        * utPLSQL can be installed in editioned schema. by @jgebal in https://github.com/utPLSQL/utPLSQL/pull/1362
        * Removed coveralls reporter by @jgebal in https://github.com/utPLSQL/utPLSQL/pull/1363
        * Clarify behavior of before/after procedures in suitepath by @jgebal in https://github.com/utPLSQL/utPLSQL/pull/1364
        * `throws` can reference exception without schema or package name by @jgebal in https://github.com/utPLSQL/utPLSQL/pull/1365
        * `throws` works with uninitialized exception variables by @jgebal in https://github.com/utPLSQL/utPLSQL/pull/1366
        
        
        **Full Changelog**: https://github.com/utPLSQL/utPLSQL/compare/v3.2.2...v.3.2.3
      RELEASE_DATE: "2026-07-10 08:30:22"
      RELEASE_URL: "https://github.com/utPLSQL/utPLSQL/releases/tag/v3.2.3"
      TARGET_BRANCH: "develop"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ env.API_TOKEN_GITHUB }}
      - uses: c-py/action-dotenv-to-setenv@v5
        with:
          env-file: .github/variables/.env
      - uses: FranzDiebold/github-env-vars-action@v2.8.0 #https://github.com/marketplace/actions/github-environment-variables-action

#      - name: Update CHANGELOG.md with release notes
#        run: .github/scripts/update_changelog.sh

#      - name: Post release announcement to org discussions
#        env:
#          GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
#        run: .github/scripts/post_release_announcement.sh

      - name: Publish release post to utplsql.github.io
        run: .github/scripts/publish_release_post.sh

